name: Build and deploy ASP.Net Core API to Azure Web App - teaskmanager-tenant

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Show repo structure
        run: ls -la
 
      - name: Show API folder
        run: ls -la TaskManager.API

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        working-directory: TaskManager.API
        run: dotnet restore TaskManager.MultiTenant.csproj

      - name: Build
        working-directory: TaskManager.API
        run: dotnet build TaskManager.MultiTenant.csproj -c Release --no-restore


      - name: Publish
        working-directory: TaskManager.API
        run: dotnet publish TaskManager.MultiTenant.csproj -c Release -o ../publish --no-restore

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-app
          path: TaskManager.API/bin/Release/net8.0/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-app
          path: app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B397A17B42374CD78C19833D3F5CA0B6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4905F2390E2B40AABEE727662A04FA1E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2D4BAAFED3EE48F1A7C7519CBAF410B8 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: teaskmanager-tenant
          slot-name: Production
          package: app
